# Generated by Django 5.2.4 on 2025-09-03 16:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Province",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Province",
                "verbose_name_plural": "Provinces",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_en", models.CharField(blank=True, max_length=100)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "province",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="districts",
                        to="districts.province",
                    ),
                ),
            ],
            options={
                "verbose_name": "District",
                "verbose_name_plural": "Districts",
                "ordering": ["province__name", "name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180), ("longitude__lte", 180)
                        ),
                        name="valid_longitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90), ("latitude__lte", 90)
                        ),
                        name="valid_latitude_range",
                    ),
                ],
                "unique_together": {("province", "name")},
            },
        ),
    ]
