# Generated by Django 5.2.4 on 2025-09-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("districts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="sigunguCd",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="province",
            name="areaCd",
            field=models.IntegerField(default=0),
        ),
    ]
