# Generated by Django 5.2.4 on 2025-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("districts", "0002_district_sigungucd_province_areacd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="sigunguCd",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="province",
            name="areaCd",
            field=models.IntegerField(unique=True),
        ),
    ]
