# Generated by Django 5.2.4 on 2025-07-31 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "preference_score",
                    models.FloatField(
                        help_text="Score between 0.0 and 1.0 indicating user's preference level",
                        verbose_name="Preference Score",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to="core.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preference",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "category"),
                        name="unique_user_category_preference",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("preference_score__gte", 0.0),
                            ("preference_score__lte", 1.0),
                        ),
                        name="valid_preference_score_range",
                    ),
                ],
            },
        ),
    ]
