# Generated by Django 5.2.4 on 2025-08-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelcourse",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelcourse",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
