# Generated by Django 5.2.4 on 2025-08-28 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelcourse",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="travelcourse",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
