# Generated by Django 5.2.4 on 2025-08-27 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel_courses", "0002_travelcourse_end_date_travelcourse_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="travelcourse",
            name="destination",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
