// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
  AccountsMeReadData,
  AccountsMeReadResponses,
  AccountsSignupCreateData,
  AccountsSignupCreateResponses,
  AuthTokenCreateData,
  AuthTokenCreateResponses,
  AuthTokenRefreshCreateData,
  AuthTokenRefreshCreateResponses,
  AuthTokenVerifyCreateData,
  AuthTokenVerifyCreateResponses,
  CategoriesListData,
  CategoriesListResponses,
  CategoriesCreateData,
  CategoriesCreateResponses,
  CategoriesDeleteData,
  CategoriesDeleteResponses,
  CategoriesReadData,
  CategoriesReadResponses,
  CategoriesPartialUpdateData,
  CategoriesPartialUpdateResponses,
  CategoriesUpdateData,
  CategoriesUpdateResponses,
  CommunityCommentsDeleteData,
  CommunityCommentsDeleteResponses,
  CommunityCommentsPartialUpdateData,
  CommunityCommentsPartialUpdateResponses,
  CommunityPostsListData,
  CommunityPostsListResponses,
  CommunityPostsCreateData,
  CommunityPostsCreateResponses,
  CommunityPostsDeleteData,
  CommunityPostsDeleteResponses,
  CommunityPostsReadData,
  CommunityPostsReadResponses,
  CommunityPostsPartialUpdateData,
  CommunityPostsPartialUpdateResponses,
  CommunityPostsCommentsListData,
  CommunityPostsCommentsListResponses,
  CommunityPostsCommentsCreateData,
  CommunityPostsCommentsCreateResponses,
  CommunityPostsLikeCreateData,
  CommunityPostsLikeCreateResponses,
  DistrictsListData,
  DistrictsListResponses,
  DistrictsReadData,
  DistrictsReadResponses,
  PlacesListData,
  PlacesListResponses,
  PlacesCreateData,
  PlacesCreateResponses,
  PlacesRecommendListData,
  PlacesRecommendListResponses,
  PlacesDeleteData,
  PlacesDeleteResponses,
  PlacesReadData,
  PlacesReadResponses,
  PlacesPartialUpdateData,
  PlacesPartialUpdateResponses,
  PlacesUpdateData,
  PlacesUpdateResponses,
  ProvincesListData,
  ProvincesListResponses,
  ProvincesReadData,
  ProvincesReadResponses,
  RoutesListData,
  RoutesListResponses,
  RoutesCreateData,
  RoutesCreateResponses,
  RoutesMyListData,
  RoutesMyListResponses,
  RoutesRecommendListData,
  RoutesRecommendListResponses,
  RoutesRecommendListErrors,
  RoutesDeleteData,
  RoutesDeleteResponses,
  RoutesReadData,
  RoutesReadResponses,
  RoutesPartialUpdateData,
  RoutesPartialUpdateResponses,
  RoutesUpdateData,
  RoutesUpdateResponses,
  TourismApiRegionalData,
  TourismApiRegionalResponses,
  TourismPoisListData,
  TourismPoisListResponses,
  TourismPoisReadData,
  TourismPoisReadResponses,
  TourismRecommendationRecommendData,
  TourismRecommendationRecommendResponses,
  TourismRecommendationRelatedData,
  TourismRecommendationRelatedResponses,
  TourismRelatedListData,
  TourismRelatedListResponses,
  TourismRelatedReadData,
  TourismRelatedReadResponses,
  TravelCoursesListData,
  TravelCoursesListResponses,
  TravelCoursesCreateData,
  TravelCoursesCreateResponses,
  TravelCoursesMyListData,
  TravelCoursesMyListResponses,
  TravelCoursesDeleteData,
  TravelCoursesDeleteResponses,
  TravelCoursesReadData,
  TravelCoursesReadResponses,
  TravelCoursesPartialUpdateData,
  TravelCoursesPartialUpdateResponses,
  TravelCoursesUpdateData,
  TravelCoursesUpdateResponses,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export class Accounts {
  public static accountsMeRead<ThrowOnError extends boolean = false>(
    options?: Options<AccountsMeReadData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      AccountsMeReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/accounts/me/",
      ...options,
    });
  }

  public static accountsSignupCreate<ThrowOnError extends boolean = false>(
    options: Options<AccountsSignupCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      AccountsSignupCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/accounts/signup/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Auth {
  /**
   * Takes a set of user credentials and returns an access and refresh JSON web
   * token pair to prove the authentication of those credentials.
   */
  public static authTokenCreate<ThrowOnError extends boolean = false>(
    options: Options<AuthTokenCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      AuthTokenCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/auth/token",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  public static authTokenRefreshCreate<ThrowOnError extends boolean = false>(
    options: Options<AuthTokenRefreshCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      AuthTokenRefreshCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/auth/token/refresh",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Takes a token and indicates if it is valid.  This view provides no
   * information about a token's fitness for a particular use.
   */
  public static authTokenVerifyCreate<ThrowOnError extends boolean = false>(
    options: Options<AuthTokenVerifyCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      AuthTokenVerifyCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/auth/token/verify",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Categories {
  public static categoriesList<ThrowOnError extends boolean = false>(
    options?: Options<CategoriesListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      CategoriesListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/",
      ...options,
    });
  }

  public static categoriesCreate<ThrowOnError extends boolean = false>(
    options: Options<CategoriesCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CategoriesCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static categoriesDelete<ThrowOnError extends boolean = false>(
    options: Options<CategoriesDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      CategoriesDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/{id}/",
      ...options,
    });
  }

  public static categoriesRead<ThrowOnError extends boolean = false>(
    options: Options<CategoriesReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      CategoriesReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/{id}/",
      ...options,
    });
  }

  public static categoriesPartialUpdate<ThrowOnError extends boolean = false>(
    options: Options<CategoriesPartialUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).patch<
      CategoriesPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static categoriesUpdate<ThrowOnError extends boolean = false>(
    options: Options<CategoriesUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      CategoriesUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/categories/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Community {
  /**
   * Delete a comment
   */
  public static communityCommentsDelete<ThrowOnError extends boolean = false>(
    options: Options<CommunityCommentsDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      CommunityCommentsDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/comments/{comment_id}/",
      ...options,
    });
  }

  /**
   * Update a comment
   */
  public static communityCommentsPartialUpdate<
    ThrowOnError extends boolean = false,
  >(options: Options<CommunityCommentsPartialUpdateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).patch<
      CommunityCommentsPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/comments/{comment_id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get list of community posts
   */
  public static communityPostsList<ThrowOnError extends boolean = false>(
    options?: Options<CommunityPostsListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      CommunityPostsListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/",
      ...options,
    });
  }

  /**
   * Create a new community post
   */
  public static communityPostsCreate<ThrowOnError extends boolean = false>(
    options: Options<CommunityPostsCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CommunityPostsCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Delete a post
   */
  public static communityPostsDelete<ThrowOnError extends boolean = false>(
    options: Options<CommunityPostsDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      CommunityPostsDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/",
      ...options,
    });
  }

  /**
   * Get post details
   */
  public static communityPostsRead<ThrowOnError extends boolean = false>(
    options: Options<CommunityPostsReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      CommunityPostsReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/",
      ...options,
    });
  }

  /**
   * Update a post
   */
  public static communityPostsPartialUpdate<
    ThrowOnError extends boolean = false,
  >(options: Options<CommunityPostsPartialUpdateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).patch<
      CommunityPostsPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Get comments for a post
   */
  public static communityPostsCommentsList<
    ThrowOnError extends boolean = false,
  >(options: Options<CommunityPostsCommentsListData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).get<
      CommunityPostsCommentsListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/comments/",
      ...options,
    });
  }

  /**
   * Create a comment on a post
   */
  public static communityPostsCommentsCreate<
    ThrowOnError extends boolean = false,
  >(options: Options<CommunityPostsCommentsCreateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      CommunityPostsCommentsCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/comments/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * Toggle like status for a post
   */
  public static communityPostsLikeCreate<ThrowOnError extends boolean = false>(
    options: Options<CommunityPostsLikeCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      CommunityPostsLikeCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/community/posts/{post_id}/like/",
      ...options,
    });
  }
}

export class Districts {
  /**
   * List all active districts with province information
   */
  public static districtsList<ThrowOnError extends boolean = false>(
    options?: Options<DistrictsListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      DistrictsListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/districts/",
      ...options,
    });
  }

  /**
   * Retrieve a specific district with full details
   */
  public static districtsRead<ThrowOnError extends boolean = false>(
    options: Options<DistrictsReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      DistrictsReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/districts/{id}/",
      ...options,
    });
  }
}

export class Places {
  public static placesList<ThrowOnError extends boolean = false>(
    options?: Options<PlacesListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      PlacesListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/",
      ...options,
    });
  }

  public static placesCreate<ThrowOnError extends boolean = false>(
    options: Options<PlacesCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      PlacesCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static placesRecommendList<ThrowOnError extends boolean = false>(
    options: Options<PlacesRecommendListData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      PlacesRecommendListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/recommend/",
      ...options,
    });
  }

  public static placesDelete<ThrowOnError extends boolean = false>(
    options: Options<PlacesDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      PlacesDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/{id}/",
      ...options,
    });
  }

  public static placesRead<ThrowOnError extends boolean = false>(
    options: Options<PlacesReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      PlacesReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/{id}/",
      ...options,
    });
  }

  public static placesPartialUpdate<ThrowOnError extends boolean = false>(
    options: Options<PlacesPartialUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).patch<
      PlacesPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static placesUpdate<ThrowOnError extends boolean = false>(
    options: Options<PlacesUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      PlacesUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/places/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Provinces {
  /**
   * List all active provinces
   */
  public static provincesList<ThrowOnError extends boolean = false>(
    options?: Options<ProvincesListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      ProvincesListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/provinces/",
      ...options,
    });
  }

  /**
   * Retrieve a specific province
   */
  public static provincesRead<ThrowOnError extends boolean = false>(
    options: Options<ProvincesReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      ProvincesReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/provinces/{id}/",
      ...options,
    });
  }
}

export class Routes {
  public static routesList<ThrowOnError extends boolean = false>(
    options?: Options<RoutesListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      RoutesListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/",
      ...options,
    });
  }

  public static routesCreate<ThrowOnError extends boolean = false>(
    options: Options<RoutesCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      RoutesCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static routesMyList<ThrowOnError extends boolean = false>(
    options?: Options<RoutesMyListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      RoutesMyListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/my/",
      ...options,
    });
  }

  public static routesRecommendList<ThrowOnError extends boolean = false>(
    options: Options<RoutesRecommendListData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      RoutesRecommendListResponses,
      RoutesRecommendListErrors,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/recommend/",
      ...options,
    });
  }

  public static routesDelete<ThrowOnError extends boolean = false>(
    options: Options<RoutesDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      RoutesDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/{id}/",
      ...options,
    });
  }

  public static routesRead<ThrowOnError extends boolean = false>(
    options: Options<RoutesReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      RoutesReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/{id}/",
      ...options,
    });
  }

  public static routesPartialUpdate<ThrowOnError extends boolean = false>(
    options: Options<RoutesPartialUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).patch<
      RoutesPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static routesUpdate<ThrowOnError extends boolean = false>(
    options: Options<RoutesUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      RoutesUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/routes/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}

export class Tourism {
  /**
   * 지역별 관광지 정보 조회 API
   * POST /api/tourism/api/regional/
   * {
   * "area_cd": "11",
   * "signgu_cd": "11530",
   * "base_ym": "202404",
   * "num_of_rows": 20,
   * "page_no": 1
   * }
   */
  public static tourismApiRegional<ThrowOnError extends boolean = false>(
    options: Options<TourismApiRegionalData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      TourismApiRegionalResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/api/regional/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * 관광지 POI 정보 조회 ViewSet
   */
  public static tourismPoisList<ThrowOnError extends boolean = false>(
    options?: Options<TourismPoisListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      TourismPoisListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/pois/",
      ...options,
    });
  }

  /**
   * 관광지 POI 정보 조회 ViewSet
   */
  public static tourismPoisRead<ThrowOnError extends boolean = false>(
    options: Options<TourismPoisReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      TourismPoisReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/pois/{id}/",
      ...options,
    });
  }

  /**
   * 사용자 위치 기반 POI 추천 API
   * POST /api/tourism/recommendation/recommend/
   * {
   * "latitude": 37.5665,
   * "longitude": 126.9780,
   * "radius_km": 10.0,
   * "max_results": 20
   * }
   */
  public static tourismRecommendationRecommend<
    ThrowOnError extends boolean = false,
  >(options: Options<TourismRecommendationRecommendData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      TourismRecommendationRecommendResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/recommendation/recommend/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * 특정 POI의 연관 관광지 조회 API
   * POST /api/tourism/recommendation/related/
   * {
   * "poi_name": "관광지명",
   * "area_cd": "11",
   * "signgu_cd": "11530"
   * }
   */
  public static tourismRecommendationRelated<
    ThrowOnError extends boolean = false,
  >(options: Options<TourismRecommendationRelatedData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).post<
      TourismRecommendationRelatedResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/recommendation/related/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  /**
   * 연관 관광지 정보 조회 ViewSet
   */
  public static tourismRelatedList<ThrowOnError extends boolean = false>(
    options?: Options<TourismRelatedListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      TourismRelatedListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/related/",
      ...options,
    });
  }

  /**
   * 연관 관광지 정보 조회 ViewSet
   */
  public static tourismRelatedRead<ThrowOnError extends boolean = false>(
    options: Options<TourismRelatedReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      TourismRelatedReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/tourism/related/{id}/",
      ...options,
    });
  }
}

export class TravelCourses {
  public static travelCoursesList<ThrowOnError extends boolean = false>(
    options?: Options<TravelCoursesListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      TravelCoursesListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/",
      ...options,
    });
  }

  public static travelCoursesCreate<ThrowOnError extends boolean = false>(
    options: Options<TravelCoursesCreateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).post<
      TravelCoursesCreateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static travelCoursesMyList<ThrowOnError extends boolean = false>(
    options?: Options<TravelCoursesMyListData, ThrowOnError>,
  ) {
    return (options?.client ?? _heyApiClient).get<
      TravelCoursesMyListResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/my/",
      ...options,
    });
  }

  public static travelCoursesDelete<ThrowOnError extends boolean = false>(
    options: Options<TravelCoursesDeleteData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).delete<
      TravelCoursesDeleteResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/{id}/",
      ...options,
    });
  }

  public static travelCoursesRead<ThrowOnError extends boolean = false>(
    options: Options<TravelCoursesReadData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).get<
      TravelCoursesReadResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/{id}/",
      ...options,
    });
  }

  public static travelCoursesPartialUpdate<
    ThrowOnError extends boolean = false,
  >(options: Options<TravelCoursesPartialUpdateData, ThrowOnError>) {
    return (options.client ?? _heyApiClient).patch<
      TravelCoursesPartialUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }

  public static travelCoursesUpdate<ThrowOnError extends boolean = false>(
    options: Options<TravelCoursesUpdateData, ThrowOnError>,
  ) {
    return (options.client ?? _heyApiClient).put<
      TravelCoursesUpdateResponses,
      unknown,
      ThrowOnError
    >({
      security: [
        {
          name: "Authorization",
          type: "apiKey",
        },
      ],
      url: "/travel_courses/{id}/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    });
  }
}
