// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from "./client";
import type {
    AccountsMeReadData,
    AccountsMeReadResponses,
    AccountsSignupCreateData,
    AccountsSignupCreateResponses,
    AuthTokenCreateData,
    AuthTokenCreateResponses,
    AuthTokenRefreshCreateData,
    AuthTokenRefreshCreateResponses,
    AuthTokenVerifyCreateData,
    AuthTokenVerifyCreateResponses,
    CategoriesListData,
    CategoriesListResponses,
    CategoriesCreateData,
    CategoriesCreateResponses,
    CategoriesDeleteData,
    CategoriesDeleteResponses,
    CategoriesReadData,
    CategoriesReadResponses,
    CategoriesPartialUpdateData,
    CategoriesPartialUpdateResponses,
    CategoriesUpdateData,
    CategoriesUpdateResponses,
    KakaomapDistanceListData,
    KakaomapDistanceListResponses,
    KakaomapMapListData,
    KakaomapMapListResponses,
    KakaomapOptimizeRouteCreateData,
    KakaomapOptimizeRouteCreateResponses,
    KakaomapRouteListData,
    KakaomapRouteListResponses,
    KakaomapSearchListData,
    KakaomapSearchListResponses,
    PlacesListData,
    PlacesListResponses,
    PlacesReadData,
    PlacesReadResponses,
    PlacesMenuItemsListData,
    PlacesMenuItemsListResponses,
    RoutesListData,
    RoutesListResponses,
    RoutesCreateData,
    RoutesCreateResponses,
    RoutesCategoriesListData,
    RoutesCategoriesListResponses,
    RoutesPreferencesListData,
    RoutesPreferencesListResponses,
    RoutesPreferencesCreateData,
    RoutesPreferencesCreateResponses,
    RoutesRecommendData,
    RoutesRecommendResponses,
    RoutesDeleteData,
    RoutesDeleteResponses,
    RoutesReadData,
    RoutesReadResponses,
    RoutesPartialUpdateData,
    RoutesPartialUpdateResponses,
    RoutesUpdateData,
    RoutesUpdateResponses,
    TourismApiRegionalData,
    TourismApiRegionalResponses,
    TourismPoisListData,
    TourismPoisListResponses,
    TourismPoisReadData,
    TourismPoisReadResponses,
    TourismRecommendationRecommendData,
    TourismRecommendationRecommendResponses,
    TourismRecommendationRelatedData,
    TourismRecommendationRelatedResponses,
    TourismRelatedListData,
    TourismRelatedListResponses,
    TourismRelatedReadData,
    TourismRelatedReadResponses,
    TravelCoursesListData,
    TravelCoursesListResponses,
    TravelCoursesCreateData,
    TravelCoursesCreateResponses,
    TravelCoursesDeleteData,
    TravelCoursesDeleteResponses,
    TravelCoursesReadData,
    TravelCoursesReadResponses,
    TravelCoursesPartialUpdateData,
    TravelCoursesPartialUpdateResponses,
    TravelCoursesUpdateData,
    TravelCoursesUpdateResponses,
} from "./types.gen";
import {
    zAccountsMeReadData,
    zAccountsMeReadResponse,
    zAccountsSignupCreateData,
    zAccountsSignupCreateResponse,
    zAuthTokenCreateData,
    zAuthTokenCreateResponse,
    zAuthTokenRefreshCreateData,
    zAuthTokenRefreshCreateResponse,
    zAuthTokenVerifyCreateData,
    zAuthTokenVerifyCreateResponse,
    zCategoriesListData,
    zCategoriesListResponse,
    zCategoriesCreateData,
    zCategoriesCreateResponse,
    zCategoriesDeleteData,
    zCategoriesReadData,
    zCategoriesReadResponse,
    zCategoriesPartialUpdateData,
    zCategoriesPartialUpdateResponse,
    zCategoriesUpdateData,
    zCategoriesUpdateResponse,
    zKakaomapDistanceListData,
    zKakaomapMapListData,
    zKakaomapOptimizeRouteCreateData,
    zKakaomapRouteListData,
    zKakaomapSearchListData,
    zPlacesListData,
    zPlacesListResponse,
    zPlacesReadData,
    zPlacesReadResponse,
    zPlacesMenuItemsListData,
    zPlacesMenuItemsListResponse,
    zRoutesListData,
    zRoutesListResponse,
    zRoutesCreateData,
    zRoutesCreateResponse,
    zRoutesCategoriesListData,
    zRoutesPreferencesListData,
    zRoutesPreferencesCreateData,
    zRoutesRecommendData,
    zRoutesRecommendResponse,
    zRoutesDeleteData,
    zRoutesReadData,
    zRoutesReadResponse,
    zRoutesPartialUpdateData,
    zRoutesPartialUpdateResponse,
    zRoutesUpdateData,
    zRoutesUpdateResponse,
    zTourismApiRegionalData,
    zTourismApiRegionalResponse,
    zTourismPoisListData,
    zTourismPoisListResponse,
    zTourismPoisReadData,
    zTourismPoisReadResponse,
    zTourismRecommendationRecommendData,
    zTourismRecommendationRecommendResponse,
    zTourismRecommendationRelatedData,
    zTourismRecommendationRelatedResponse,
    zTourismRelatedListData,
    zTourismRelatedListResponse,
    zTourismRelatedReadData,
    zTourismRelatedReadResponse,
    zTravelCoursesListData,
    zTravelCoursesListResponse,
    zTravelCoursesCreateData,
    zTravelCoursesCreateResponse,
    zTravelCoursesDeleteData,
    zTravelCoursesReadData,
    zTravelCoursesReadResponse,
    zTravelCoursesPartialUpdateData,
    zTravelCoursesPartialUpdateResponse,
    zTravelCoursesUpdateData,
    zTravelCoursesUpdateResponse,
} from "./zod.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean
> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class Accounts {
    public static accountsMeRead<ThrowOnError extends boolean = false>(
        options?: Options<AccountsMeReadData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            AccountsMeReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zAccountsMeReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zAccountsMeReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/accounts/me/",
            ...options,
        });
    }

    public static accountsSignupCreate<ThrowOnError extends boolean = false>(
        options: Options<AccountsSignupCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            AccountsSignupCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zAccountsSignupCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zAccountsSignupCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/accounts/signup/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }
}

export class Auth {
    /**
     * Takes a set of user credentials and returns an access and refresh JSON web
     * token pair to prove the authentication of those credentials.
     */
    public static authTokenCreate<ThrowOnError extends boolean = false>(
        options: Options<AuthTokenCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            AuthTokenCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zAuthTokenCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zAuthTokenCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/auth/token",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    public static authTokenRefreshCreate<ThrowOnError extends boolean = false>(
        options: Options<AuthTokenRefreshCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            AuthTokenRefreshCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zAuthTokenRefreshCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zAuthTokenRefreshCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/auth/token/refresh",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * Takes a token and indicates if it is valid.  This view provides no
     * information about a token's fitness for a particular use.
     */
    public static authTokenVerifyCreate<ThrowOnError extends boolean = false>(
        options: Options<AuthTokenVerifyCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            AuthTokenVerifyCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zAuthTokenVerifyCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zAuthTokenVerifyCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/auth/token/verify",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }
}

export class Categories {
    public static categoriesList<ThrowOnError extends boolean = false>(
        options?: Options<CategoriesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            CategoriesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zCategoriesListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/",
            ...options,
        });
    }

    public static categoriesCreate<ThrowOnError extends boolean = false>(
        options: Options<CategoriesCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            CategoriesCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zCategoriesCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static categoriesDelete<ThrowOnError extends boolean = false>(
        options: Options<CategoriesDeleteData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).delete<
            CategoriesDeleteResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesDeleteData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/{id}/",
            ...options,
        });
    }

    public static categoriesRead<ThrowOnError extends boolean = false>(
        options: Options<CategoriesReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            CategoriesReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zCategoriesReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/{id}/",
            ...options,
        });
    }

    public static categoriesPartialUpdate<ThrowOnError extends boolean = false>(
        options: Options<CategoriesPartialUpdateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).patch<
            CategoriesPartialUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesPartialUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zCategoriesPartialUpdateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static categoriesUpdate<ThrowOnError extends boolean = false>(
        options: Options<CategoriesUpdateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).put<
            CategoriesUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zCategoriesUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zCategoriesUpdateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/categories/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }
}

export class Kakaomap {
    /**
     * Calculate straight-line distance between two points
     */
    public static kakaomapDistanceList<ThrowOnError extends boolean = false>(
        options?: Options<KakaomapDistanceListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            KakaomapDistanceListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zKakaomapDistanceListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/kakaomap/distance/",
            ...options,
        });
    }

    /**
     * Get Kakao Map static image URL
     */
    public static kakaomapMapList<ThrowOnError extends boolean = false>(
        options?: Options<KakaomapMapListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            KakaomapMapListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zKakaomapMapListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/kakaomap/map/",
            ...options,
        });
    }

    /**
     * Calculate total distance for multiple points (route optimization)
     */
    public static routeCreate<ThrowOnError extends boolean = false>(
        options?: Options<KakaomapOptimizeRouteCreateData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).post<
            KakaomapOptimizeRouteCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zKakaomapOptimizeRouteCreateData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/kakaomap/optimize-route/",
            ...options,
        });
    }

    /**
     * Get route information (distance, duration) between two points using Kakao Map API
     */
    public static kakaomapRouteList<ThrowOnError extends boolean = false>(
        options?: Options<KakaomapRouteListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            KakaomapRouteListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zKakaomapRouteListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/kakaomap/route/",
            ...options,
        });
    }

    /**
     * Search places from Kakao Local API
     */
    public static kakaomapSearchList<ThrowOnError extends boolean = false>(
        options?: Options<KakaomapSearchListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            KakaomapSearchListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zKakaomapSearchListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/kakaomap/search/",
            ...options,
        });
    }
}

export class Places {
    public static placesList<ThrowOnError extends boolean = false>(
        options?: Options<PlacesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            PlacesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zPlacesListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zPlacesListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/places/",
            ...options,
        });
    }

    public static placesRead<ThrowOnError extends boolean = false>(
        options: Options<PlacesReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            PlacesReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zPlacesReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zPlacesReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/places/{id}/",
            ...options,
        });
    }

    public static itemsList<ThrowOnError extends boolean = false>(
        options: Options<PlacesMenuItemsListData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            PlacesMenuItemsListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zPlacesMenuItemsListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zPlacesMenuItemsListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/places/{id}/menu-items/",
            ...options,
        });
    }
}

export class Routes {
    public static routesList<ThrowOnError extends boolean = false>(
        options?: Options<RoutesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            RoutesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/",
            ...options,
        });
    }

    public static routesCreate<ThrowOnError extends boolean = false>(
        options: Options<RoutesCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            RoutesCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * Get list of all available categories.
     */
    public static routesCategoriesList<ThrowOnError extends boolean = false>(
        options?: Options<RoutesCategoriesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            RoutesCategoriesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesCategoriesListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/categories/",
            ...options,
        });
    }

    public static routesPreferencesList<ThrowOnError extends boolean = false>(
        options?: Options<RoutesPreferencesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            RoutesPreferencesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesPreferencesListData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/preferences/",
            ...options,
        });
    }

    public static routesPreferencesCreate<ThrowOnError extends boolean = false>(
        options?: Options<RoutesPreferencesCreateData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).post<
            RoutesPreferencesCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesPreferencesCreateData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/preferences/",
            ...options,
        });
    }

    /**
     * Generate route recommendations based on user preferences and location.
     * Expected JSON payload:
     * {
     * "user_lat": 37.5665,
     * "user_lng": 126.9780,
     * "max_places": 5,
     * "max_distance_km": 20.0,
     * "category_filter": ["카페", "한식"] // optional
     * }
     */
    public static routesRecommend<ThrowOnError extends boolean = false>(
        options: Options<RoutesRecommendData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            RoutesRecommendResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesRecommendData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesRecommendResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/recommend/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static routesDelete<ThrowOnError extends boolean = false>(
        options: Options<RoutesDeleteData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).delete<
            RoutesDeleteResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesDeleteData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/{id}/",
            ...options,
        });
    }

    public static routesRead<ThrowOnError extends boolean = false>(
        options: Options<RoutesReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            RoutesReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/{id}/",
            ...options,
        });
    }

    public static routesPartialUpdate<ThrowOnError extends boolean = false>(
        options: Options<RoutesPartialUpdateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).patch<
            RoutesPartialUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesPartialUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesPartialUpdateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static routesUpdate<ThrowOnError extends boolean = false>(
        options: Options<RoutesUpdateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).put<
            RoutesUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zRoutesUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zRoutesUpdateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/routes/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }
}

export class Tourism {
    /**
     * 지역별 관광지 정보 조회 API
     * POST /api/tourism/api/regional/
     * {
     * "area_cd": "11",
     * "signgu_cd": "11530",
     * "base_ym": "202404",
     * "num_of_rows": 20,
     * "page_no": 1
     * }
     */
    public static tourismApiRegional<ThrowOnError extends boolean = false>(
        options: Options<TourismApiRegionalData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            TourismApiRegionalResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismApiRegionalData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismApiRegionalResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/api/regional/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * 관광지 POI 정보 조회 ViewSet
     */
    public static tourismPoisList<ThrowOnError extends boolean = false>(
        options?: Options<TourismPoisListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            TourismPoisListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismPoisListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismPoisListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/pois/",
            ...options,
        });
    }

    /**
     * 관광지 POI 정보 조회 ViewSet
     */
    public static tourismPoisRead<ThrowOnError extends boolean = false>(
        options: Options<TourismPoisReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            TourismPoisReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismPoisReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismPoisReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/pois/{id}/",
            ...options,
        });
    }

    /**
     * 사용자 위치 기반 POI 추천 API
     * POST /api/tourism/recommendation/recommend/
     * {
     * "latitude": 37.5665,
     * "longitude": 126.9780,
     * "radius_km": 10.0,
     * "max_results": 20
     * }
     */
    public static tourismRecommendationRecommend<
        ThrowOnError extends boolean = false
    >(options: Options<TourismRecommendationRecommendData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<
            TourismRecommendationRecommendResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismRecommendationRecommendData.parseAsync(
                    data
                );
            },
            responseValidator: async (data) => {
                return await zTourismRecommendationRecommendResponse.parseAsync(
                    data
                );
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/recommendation/recommend/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * 특정 POI의 연관 관광지 조회 API
     * POST /api/tourism/recommendation/related/
     * {
     * "poi_name": "관광지명",
     * "area_cd": "11",
     * "signgu_cd": "11530"
     * }
     */
    public static tourismRecommendationRelated<
        ThrowOnError extends boolean = false
    >(options: Options<TourismRecommendationRelatedData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<
            TourismRecommendationRelatedResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismRecommendationRelatedData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismRecommendationRelatedResponse.parseAsync(
                    data
                );
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/recommendation/related/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    /**
     * 연관 관광지 정보 조회 ViewSet
     */
    public static tourismRelatedList<ThrowOnError extends boolean = false>(
        options?: Options<TourismRelatedListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            TourismRelatedListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismRelatedListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismRelatedListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/related/",
            ...options,
        });
    }

    /**
     * 연관 관광지 정보 조회 ViewSet
     */
    public static tourismRelatedRead<ThrowOnError extends boolean = false>(
        options: Options<TourismRelatedReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            TourismRelatedReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTourismRelatedReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTourismRelatedReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/tourism/related/{id}/",
            ...options,
        });
    }
}

export class TravelCourses {
    public static travelCoursesList<ThrowOnError extends boolean = false>(
        options?: Options<TravelCoursesListData, ThrowOnError>
    ) {
        return (options?.client ?? _heyApiClient).get<
            TravelCoursesListResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesListData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTravelCoursesListResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/",
            ...options,
        });
    }

    public static travelCoursesCreate<ThrowOnError extends boolean = false>(
        options: Options<TravelCoursesCreateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).post<
            TravelCoursesCreateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesCreateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTravelCoursesCreateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static travelCoursesDelete<ThrowOnError extends boolean = false>(
        options: Options<TravelCoursesDeleteData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).delete<
            TravelCoursesDeleteResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesDeleteData.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/{id}/",
            ...options,
        });
    }

    public static travelCoursesRead<ThrowOnError extends boolean = false>(
        options: Options<TravelCoursesReadData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).get<
            TravelCoursesReadResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesReadData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTravelCoursesReadResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/{id}/",
            ...options,
        });
    }

    public static travelCoursesPartialUpdate<
        ThrowOnError extends boolean = false
    >(options: Options<TravelCoursesPartialUpdateData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<
            TravelCoursesPartialUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesPartialUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTravelCoursesPartialUpdateResponse.parseAsync(
                    data
                );
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }

    public static travelCoursesUpdate<ThrowOnError extends boolean = false>(
        options: Options<TravelCoursesUpdateData, ThrowOnError>
    ) {
        return (options.client ?? _heyApiClient).put<
            TravelCoursesUpdateResponses,
            unknown,
            ThrowOnError
        >({
            requestValidator: async (data) => {
                return await zTravelCoursesUpdateData.parseAsync(data);
            },
            responseValidator: async (data) => {
                return await zTravelCoursesUpdateResponse.parseAsync(data);
            },
            security: [
                {
                    name: "Authorization",
                    type: "apiKey",
                },
            ],
            url: "/travel_courses/{id}/",
            ...options,
            headers: {
                "Content-Type": "application/json",
                ...options.headers,
            },
        });
    }
}
