// This file is auto-generated by @hey-api/openapi-ts

export type Route = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Created by
     */
    created_by?: number | null;
    readonly places?: Array<string>;
};

export type RegionalTourismRequest = {
    /**
     * Area cd
     * 지역코드 (예: '11' for 서울)
     */
    area_cd: string;
    /**
     * Signgu cd
     * 시군구코드 (예: '11530' for 구로구)
     */
    signgu_cd: string;
    /**
     * Base ym
     * 기준연월 (YYYYMM 형식, 기본값: 현재월)
     */
    base_ym?: string;
    /**
     * Num of rows
     * 한 페이지 결과 수 (기본값: 20)
     */
    num_of_rows?: number;
    /**
     * Page no
     * 페이지 번호 (기본값: 1)
     */
    page_no?: number;
};

export type TourismPoi = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * 중심지관광지코드
     */
    hub_tats_cd: string;
    /**
     * 중심지관광지명
     */
    hub_tats_nm: string;
    /**
     * X좌표값(경도)
     */
    map_x: number;
    /**
     * Y좌표값(위도)
     */
    map_y: number;
    /**
     * 지역코드
     */
    area_cd: string;
    /**
     * 지역명
     */
    area_nm: string;
    /**
     * 시군구코드
     */
    signgu_cd: string;
    /**
     * 시군구명
     */
    signgu_nm: string;
    /**
     * 중심지카테고리대분류명
     */
    hub_ctgry_lcls_nm?: string;
    /**
     * 중심지카테고리중분류명
     */
    hub_ctgry_mcls_nm?: string;
    /**
     * 중심지순위
     */
    hub_rank: number;
    /**
     * 외부 링크
     */
    external_url?: string;
    /**
     * 전화번호
     */
    phone_number?: string;
    /**
     * 주소
     */
    address?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type PoiRecommendationRequest = {
    /**
     * Latitude
     * 사용자 위도 (-90 ~ 90)
     */
    latitude: number;
    /**
     * Longitude
     * 사용자 경도 (-180 ~ 180)
     */
    longitude: number;
    /**
     * Radius km
     * 추천 반경 (km, 기본값: 10.0)
     */
    radius_km?: number;
    /**
     * Max results
     * 최대 추천 개수 (기본값: 20)
     */
    max_results?: number;
};

export type RelatedPoiRequest = {
    /**
     * Poi name
     * 관광지명
     */
    poi_name: string;
    /**
     * Area cd
     * 지역코드
     */
    area_cd: string;
    /**
     * Signgu cd
     * 시군구코드
     */
    signgu_cd: string;
};

export type RelatedTourism = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * 기준관광지명
     */
    base_tats_nm: string;
    /**
     * 기준관광지지역코드
     */
    base_area_cd: string;
    /**
     * 기준관광지지역명
     */
    base_area_nm?: string;
    /**
     * 연관관광지코드
     */
    rite_tats_cd: string;
    /**
     * 연관관광지명
     */
    rite_tats_nm: string;
    /**
     * 연관관광지지역코드
     */
    rite_regn_cd: string;
    /**
     * 연관관광지지역명
     */
    rite_regn_nm?: string;
    /**
     * 연관카테고리대분류명
     */
    rite_ctgry_lcls_nm?: string;
    /**
     * 연관카테고리중분류명
     */
    rite_ctgry_mcls_nm?: string;
    /**
     * 연관순위
     */
    rite_rank: number;
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type TravelCourseRoute = {
    /**
     * Route id
     */
    route_id: string;
    /**
     * Sequence
     */
    sequence?: number;
};

export type TravelCourse = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
    routes: Array<TravelCourseRoute>;
};

export type KakaomapDistanceListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kakaomap/distance/';
};

export type KakaomapDistanceListResponses = {
    200: unknown;
};

export type KakaomapMapListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kakaomap/map/';
};

export type KakaomapMapListResponses = {
    200: unknown;
};

export type KakaomapOptimizeRouteCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kakaomap/optimize-route/';
};

export type KakaomapOptimizeRouteCreateResponses = {
    201: unknown;
};

export type KakaomapRouteListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kakaomap/route/';
};

export type KakaomapRouteListResponses = {
    200: unknown;
};

export type KakaomapSearchListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/kakaomap/search/';
};

export type KakaomapSearchListResponses = {
    200: unknown;
};

export type RoutesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/';
};

export type RoutesListResponses = {
    200: Array<Route>;
};

export type RoutesListResponse = RoutesListResponses[keyof RoutesListResponses];

export type RoutesCreateData = {
    body: Route;
    path?: never;
    query?: never;
    url: '/routes/';
};

export type RoutesCreateResponses = {
    201: Route;
};

export type RoutesCreateResponse = RoutesCreateResponses[keyof RoutesCreateResponses];

export type RoutesCategoriesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/categories/';
};

export type RoutesCategoriesListResponses = {
    200: unknown;
};

export type RoutesPreferencesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/preferences/';
};

export type RoutesPreferencesListResponses = {
    200: unknown;
};

export type RoutesPreferencesCreateData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/preferences/';
};

export type RoutesPreferencesCreateResponses = {
    201: unknown;
};

export type RoutesRecommendData = {
    body: Route;
    path?: never;
    query?: never;
    url: '/routes/recommend/';
};

export type RoutesRecommendResponses = {
    201: Route;
};

export type RoutesRecommendResponse = RoutesRecommendResponses[keyof RoutesRecommendResponses];

export type RoutesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesDeleteResponses = {
    204: unknown;
};

export type RoutesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesReadResponses = {
    200: Route;
};

export type RoutesReadResponse = RoutesReadResponses[keyof RoutesReadResponses];

export type RoutesPartialUpdateData = {
    body: Route;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesPartialUpdateResponses = {
    200: Route;
};

export type RoutesPartialUpdateResponse = RoutesPartialUpdateResponses[keyof RoutesPartialUpdateResponses];

export type RoutesUpdateData = {
    body: Route;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesUpdateResponses = {
    200: Route;
};

export type RoutesUpdateResponse = RoutesUpdateResponses[keyof RoutesUpdateResponses];

export type TourismApiRegionalData = {
    body: RegionalTourismRequest;
    path?: never;
    query?: never;
    url: '/tourism/api/regional/';
};

export type TourismApiRegionalResponses = {
    201: RegionalTourismRequest;
};

export type TourismApiRegionalResponse = TourismApiRegionalResponses[keyof TourismApiRegionalResponses];

export type TourismPoisListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourism/pois/';
};

export type TourismPoisListResponses = {
    200: Array<TourismPoi>;
};

export type TourismPoisListResponse = TourismPoisListResponses[keyof TourismPoisListResponses];

export type TourismPoisReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this 관광지 POI.
         */
        id: string;
    };
    query?: never;
    url: '/tourism/pois/{id}/';
};

export type TourismPoisReadResponses = {
    200: TourismPoi;
};

export type TourismPoisReadResponse = TourismPoisReadResponses[keyof TourismPoisReadResponses];

export type TourismRecommendationRecommendData = {
    body: PoiRecommendationRequest;
    path?: never;
    query?: never;
    url: '/tourism/recommendation/recommend/';
};

export type TourismRecommendationRecommendResponses = {
    201: PoiRecommendationRequest;
};

export type TourismRecommendationRecommendResponse = TourismRecommendationRecommendResponses[keyof TourismRecommendationRecommendResponses];

export type TourismRecommendationRelatedData = {
    body: RelatedPoiRequest;
    path?: never;
    query?: never;
    url: '/tourism/recommendation/related/';
};

export type TourismRecommendationRelatedResponses = {
    201: RelatedPoiRequest;
};

export type TourismRecommendationRelatedResponse = TourismRecommendationRelatedResponses[keyof TourismRecommendationRelatedResponses];

export type TourismRelatedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourism/related/';
};

export type TourismRelatedListResponses = {
    200: Array<RelatedTourism>;
};

export type TourismRelatedListResponse = TourismRelatedListResponses[keyof TourismRelatedListResponses];

export type TourismRelatedReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this 연관 관광지.
         */
        id: string;
    };
    query?: never;
    url: '/tourism/related/{id}/';
};

export type TourismRelatedReadResponses = {
    200: RelatedTourism;
};

export type TourismRelatedReadResponse = TourismRelatedReadResponses[keyof TourismRelatedReadResponses];

export type TravelCoursesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/travel_courses/';
};

export type TravelCoursesListResponses = {
    200: Array<TravelCourse>;
};

export type TravelCoursesListResponse = TravelCoursesListResponses[keyof TravelCoursesListResponses];

export type TravelCoursesCreateData = {
    body: TravelCourse;
    path?: never;
    query?: never;
    url: '/travel_courses/';
};

export type TravelCoursesCreateResponses = {
    201: TravelCourse;
};

export type TravelCoursesCreateResponse = TravelCoursesCreateResponses[keyof TravelCoursesCreateResponses];

export type TravelCoursesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesDeleteResponses = {
    204: unknown;
};

export type TravelCoursesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesReadResponses = {
    200: TravelCourse;
};

export type TravelCoursesReadResponse = TravelCoursesReadResponses[keyof TravelCoursesReadResponses];

export type TravelCoursesPartialUpdateData = {
    body: TravelCourse;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesPartialUpdateResponses = {
    200: TravelCourse;
};

export type TravelCoursesPartialUpdateResponse = TravelCoursesPartialUpdateResponses[keyof TravelCoursesPartialUpdateResponses];

export type TravelCoursesUpdateData = {
    body: TravelCourse;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesUpdateResponses = {
    200: TravelCourse;
};

export type TravelCoursesUpdateResponse = TravelCoursesUpdateResponses[keyof TravelCoursesUpdateResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};
