// This file is auto-generated by @hey-api/openapi-ts

export type UserDetail = {
    /**
     * ID
     */
    readonly id?: number;
    /**
     * Name
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Login Method
     */
    login_method?: 'email' | 'kakao' | 'google';
    /**
     * Profile Image URL
     */
    profile_image_url?: string | null;
    /**
     * Date joined
     */
    readonly date_joined?: string;
};

export type User = {
    /**
     * Name
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Password confirm
     */
    password_confirm: string;
    /**
     * Login Method
     */
    login_method?: 'email' | 'kakao' | 'google';
};

export type TokenObtainPair = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

export type TokenRefresh = {
    /**
     * Refresh
     */
    refresh: string;
    /**
     * Access
     */
    readonly access?: string;
};

export type TokenVerify = {
    /**
     * Token
     */
    token: string;
};

export type Category = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Icon
     */
    icon?: string;
    /**
     * Color
     */
    color?: string;
    /**
     * Category type
     */
    category_type?: 'korean' | 'western' | 'japanese' | 'chinese' | 'asian' | 'snack' | 'hamburger' | 'pizza' | 'seafood' | 'meat' | 'bakery' | 'pub';
    /**
     * Is active
     */
    is_active?: boolean;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
};

export type DistrictList = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Name en
     */
    name_en?: string;
    /**
     * Longitude
     */
    longitude: string;
    /**
     * Latitude
     */
    latitude: string;
    /**
     * Province name
     */
    readonly province_name?: string;
    /**
     * Is active
     */
    is_active?: boolean;
};

export type Province = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Name en
     */
    name_en?: string;
    /**
     * Is active
     */
    is_active?: boolean;
};

export type District = {
    /**
     * Id
     */
    readonly id?: string;
    province?: Province;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Name en
     */
    name_en?: string;
    /**
     * Longitude
     */
    longitude: string;
    /**
     * Latitude
     */
    latitude: string;
    /**
     * Is active
     */
    is_active?: boolean;
};

export type Place = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lng
     */
    lng: number;
    /**
     * Phone number
     */
    phone_number?: string;
    /**
     * Avg rating
     */
    avg_rating?: number | null;
    /**
     * Place type
     */
    place_type?: 'RESTAURANT' | 'ATTRACTION' | 'SHOPPING' | 'ETC';
    /**
     * Address
     */
    address?: string;
    /**
     * Road address
     */
    road_address?: string;
    /**
     * External id
     */
    external_id: string;
    /**
     * External url
     */
    external_url?: string;
    /**
     * Created by
     */
    created_by?: number | null;
};

export type PlaceRecommend = {
    /**
     * Name
     */
    name: string;
    /**
     * Lat
     */
    lat: number;
    /**
     * Lng
     */
    lng: number;
    /**
     * Phone number
     */
    phone_number: string | null;
    /**
     * Place type
     */
    place_type: string;
    /**
     * Address
     */
    address: string | null;
    /**
     * Road address
     */
    road_address: string | null;
    /**
     * External id
     */
    external_id: string;
    /**
     * External url
     */
    external_url: string | null;
};

export type PlaceRecommendOutput = {
    places: Array<PlaceRecommend>;
};

export type Route = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
    /**
     * Updated at
     */
    readonly updated_at?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
    /**
     * Created by
     */
    created_by?: number | null;
    readonly places?: Array<string>;
};

export type RouteRecommendationOutput = {
    /**
     * List of route options with places, distances, and metadata
     */
    routes: Array<{
        [key: string]: string | null;
    }>;
    /**
     * User location
     */
    user_location: {
        [key: string]: number;
    };
};

export type RegionalTourismRequest = {
    /**
     * Area cd
     * 지역코드 (예: '11' for 서울)
     */
    area_cd: string;
    /**
     * Signgu cd
     * 시군구코드 (예: '11530' for 구로구)
     */
    signgu_cd: string;
    /**
     * Base ym
     * 기준연월 (YYYYMM 형식, 기본값: 현재월)
     */
    base_ym?: string;
    /**
     * Num of rows
     * 한 페이지 결과 수 (기본값: 20)
     */
    num_of_rows?: number;
    /**
     * Page no
     * 페이지 번호 (기본값: 1)
     */
    page_no?: number;
};

export type TourismPoi = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * 중심지관광지코드
     */
    hub_tats_cd: string;
    /**
     * 중심지관광지명
     */
    hub_tats_nm: string;
    /**
     * X좌표값(경도)
     */
    map_x: number;
    /**
     * Y좌표값(위도)
     */
    map_y: number;
    /**
     * 지역코드
     */
    area_cd: string;
    /**
     * 지역명
     */
    area_nm: string;
    /**
     * 시군구코드
     */
    signgu_cd: string;
    /**
     * 시군구명
     */
    signgu_nm: string;
    /**
     * 중심지카테고리대분류명
     */
    hub_ctgry_lcls_nm?: string;
    /**
     * 중심지카테고리중분류명
     */
    hub_ctgry_mcls_nm?: string;
    /**
     * 중심지순위
     */
    hub_rank: number;
    /**
     * 외부 링크
     */
    external_url?: string;
    /**
     * 전화번호
     */
    phone_number?: string;
    /**
     * 주소
     */
    address?: string;
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type PoiRecommendationRequest = {
    /**
     * Latitude
     * 사용자 위도 (-90 ~ 90)
     */
    latitude: number;
    /**
     * Longitude
     * 사용자 경도 (-180 ~ 180)
     */
    longitude: number;
    /**
     * Radius km
     * 추천 반경 (km, 기본값: 10.0)
     */
    radius_km?: number;
    /**
     * Max results
     * 최대 추천 개수 (기본값: 20)
     */
    max_results?: number;
};

export type RelatedPoiRequest = {
    /**
     * Poi name
     * 관광지명
     */
    poi_name: string;
    /**
     * Area cd
     * 지역코드
     */
    area_cd: string;
    /**
     * Signgu cd
     * 시군구코드
     */
    signgu_cd: string;
};

export type RelatedTourism = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * 기준관광지명
     */
    base_tats_nm: string;
    /**
     * 기준관광지지역코드
     */
    base_area_cd: string;
    /**
     * 기준관광지지역명
     */
    base_area_nm?: string;
    /**
     * 연관관광지코드
     */
    rite_tats_cd: string;
    /**
     * 연관관광지명
     */
    rite_tats_nm: string;
    /**
     * 연관관광지지역코드
     */
    rite_regn_cd: string;
    /**
     * 연관관광지지역명
     */
    rite_regn_nm?: string;
    /**
     * 연관카테고리대분류명
     */
    rite_ctgry_lcls_nm?: string;
    /**
     * 연관카테고리중분류명
     */
    rite_ctgry_mcls_nm?: string;
    /**
     * 연관순위
     */
    rite_rank: number;
    /**
     * Created at
     */
    readonly created_at?: string;
};

export type TravelCourseRoute = {
    /**
     * Route id
     */
    route_id: string;
    /**
     * Sequence
     */
    sequence?: number;
};

export type TravelCourse = {
    /**
     * Id
     */
    readonly id?: string;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string;
    routes: Array<TravelCourseRoute>;
    /**
     * Start date
     */
    start_date?: string | null;
    /**
     * End date
     */
    end_date?: string | null;
    /**
     * Destination
     */
    destination?: string | null;
};

export type AccountsMeReadData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/accounts/me/';
};

export type AccountsMeReadResponses = {
    200: UserDetail;
};

export type AccountsMeReadResponse = AccountsMeReadResponses[keyof AccountsMeReadResponses];

export type AccountsSignupCreateData = {
    body: User;
    path?: never;
    query?: never;
    url: '/accounts/signup/';
};

export type AccountsSignupCreateResponses = {
    201: User;
};

export type AccountsSignupCreateResponse = AccountsSignupCreateResponses[keyof AccountsSignupCreateResponses];

export type AuthTokenCreateData = {
    body: TokenObtainPair;
    path?: never;
    query?: never;
    url: '/auth/token';
};

export type AuthTokenCreateResponses = {
    201: TokenObtainPair;
};

export type AuthTokenCreateResponse = AuthTokenCreateResponses[keyof AuthTokenCreateResponses];

export type AuthTokenRefreshCreateData = {
    body: TokenRefresh;
    path?: never;
    query?: never;
    url: '/auth/token/refresh';
};

export type AuthTokenRefreshCreateResponses = {
    201: TokenRefresh;
};

export type AuthTokenRefreshCreateResponse = AuthTokenRefreshCreateResponses[keyof AuthTokenRefreshCreateResponses];

export type AuthTokenVerifyCreateData = {
    body: TokenVerify;
    path?: never;
    query?: never;
    url: '/auth/token/verify';
};

export type AuthTokenVerifyCreateResponses = {
    201: TokenVerify;
};

export type AuthTokenVerifyCreateResponse = AuthTokenVerifyCreateResponses[keyof AuthTokenVerifyCreateResponses];

export type CategoriesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type CategoriesListResponses = {
    200: Array<Category>;
};

export type CategoriesListResponse = CategoriesListResponses[keyof CategoriesListResponses];

export type CategoriesCreateData = {
    body: Category;
    path?: never;
    query?: never;
    url: '/categories/';
};

export type CategoriesCreateResponses = {
    201: Category;
};

export type CategoriesCreateResponse = CategoriesCreateResponses[keyof CategoriesCreateResponses];

export type CategoriesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this category.
         */
        id: string;
    };
    query?: never;
    url: '/categories/{id}/';
};

export type CategoriesDeleteResponses = {
    204: unknown;
};

export type CategoriesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this category.
         */
        id: string;
    };
    query?: never;
    url: '/categories/{id}/';
};

export type CategoriesReadResponses = {
    200: Category;
};

export type CategoriesReadResponse = CategoriesReadResponses[keyof CategoriesReadResponses];

export type CategoriesPartialUpdateData = {
    body: Category;
    path: {
        /**
         * A UUID string identifying this category.
         */
        id: string;
    };
    query?: never;
    url: '/categories/{id}/';
};

export type CategoriesPartialUpdateResponses = {
    200: Category;
};

export type CategoriesPartialUpdateResponse = CategoriesPartialUpdateResponses[keyof CategoriesPartialUpdateResponses];

export type CategoriesUpdateData = {
    body: Category;
    path: {
        /**
         * A UUID string identifying this category.
         */
        id: string;
    };
    query?: never;
    url: '/categories/{id}/';
};

export type CategoriesUpdateResponses = {
    200: Category;
};

export type CategoriesUpdateResponse = CategoriesUpdateResponses[keyof CategoriesUpdateResponses];

export type DistrictsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/districts/';
};

export type DistrictsListResponses = {
    200: Array<DistrictList>;
};

export type DistrictsListResponse = DistrictsListResponses[keyof DistrictsListResponses];

export type DistrictsReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this District.
         */
        id: string;
    };
    query?: never;
    url: '/districts/{id}/';
};

export type DistrictsReadResponses = {
    200: District;
};

export type DistrictsReadResponse = DistrictsReadResponses[keyof DistrictsReadResponses];

export type PlacesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/places/';
};

export type PlacesListResponses = {
    200: Array<Place>;
};

export type PlacesListResponse = PlacesListResponses[keyof PlacesListResponses];

export type PlacesCreateData = {
    body: Place;
    path?: never;
    query?: never;
    url: '/places/';
};

export type PlacesCreateResponses = {
    201: Place;
};

export type PlacesCreateResponse = PlacesCreateResponses[keyof PlacesCreateResponses];

export type PlacesRecommendListData = {
    body?: never;
    path?: never;
    query: {
        lat: number;
        lng: number;
        max_distance_km?: number | null;
        limit?: number | null;
        category_filter?: Array<string> | null;
    };
    url: '/places/recommend/';
};

export type PlacesRecommendListResponses = {
    200: PlaceRecommendOutput;
};

export type PlacesRecommendListResponse = PlacesRecommendListResponses[keyof PlacesRecommendListResponses];

export type PlacesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this place.
         */
        id: string;
    };
    query?: never;
    url: '/places/{id}/';
};

export type PlacesDeleteResponses = {
    204: unknown;
};

export type PlacesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this place.
         */
        id: string;
    };
    query?: never;
    url: '/places/{id}/';
};

export type PlacesReadResponses = {
    200: Place;
};

export type PlacesReadResponse = PlacesReadResponses[keyof PlacesReadResponses];

export type PlacesPartialUpdateData = {
    body: Place;
    path: {
        /**
         * A UUID string identifying this place.
         */
        id: string;
    };
    query?: never;
    url: '/places/{id}/';
};

export type PlacesPartialUpdateResponses = {
    200: Place;
};

export type PlacesPartialUpdateResponse = PlacesPartialUpdateResponses[keyof PlacesPartialUpdateResponses];

export type PlacesUpdateData = {
    body: Place;
    path: {
        /**
         * A UUID string identifying this place.
         */
        id: string;
    };
    query?: never;
    url: '/places/{id}/';
};

export type PlacesUpdateResponses = {
    200: Place;
};

export type PlacesUpdateResponse = PlacesUpdateResponses[keyof PlacesUpdateResponses];

export type ProvincesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/provinces/';
};

export type ProvincesListResponses = {
    200: Array<Province>;
};

export type ProvincesListResponse = ProvincesListResponses[keyof ProvincesListResponses];

export type ProvincesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this Province.
         */
        id: string;
    };
    query?: never;
    url: '/provinces/{id}/';
};

export type ProvincesReadResponses = {
    200: Province;
};

export type ProvincesReadResponse = ProvincesReadResponses[keyof ProvincesReadResponses];

export type RoutesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/';
};

export type RoutesListResponses = {
    200: Array<Route>;
};

export type RoutesListResponse = RoutesListResponses[keyof RoutesListResponses];

export type RoutesCreateData = {
    body: Route;
    path?: never;
    query?: never;
    url: '/routes/';
};

export type RoutesCreateResponses = {
    201: Route;
};

export type RoutesCreateResponse = RoutesCreateResponses[keyof RoutesCreateResponses];

export type RoutesMyListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/routes/my/';
};

export type RoutesMyListResponses = {
    200: Array<Route>;
};

export type RoutesMyListResponse = RoutesMyListResponses[keyof RoutesMyListResponses];

export type RoutesRecommendListData = {
    body?: never;
    path?: never;
    query: {
        lat: number;
        lng: number;
        max_distance_km?: number | null;
        limit?: number | null;
        category_filter?: Array<string> | null;
    };
    url: '/routes/recommend/';
};

export type RoutesRecommendListErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type RoutesRecommendListResponses = {
    200: RouteRecommendationOutput;
};

export type RoutesRecommendListResponse = RoutesRecommendListResponses[keyof RoutesRecommendListResponses];

export type RoutesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesDeleteResponses = {
    204: unknown;
};

export type RoutesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesReadResponses = {
    200: Route;
};

export type RoutesReadResponse = RoutesReadResponses[keyof RoutesReadResponses];

export type RoutesPartialUpdateData = {
    body: Route;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesPartialUpdateResponses = {
    200: Route;
};

export type RoutesPartialUpdateResponse = RoutesPartialUpdateResponses[keyof RoutesPartialUpdateResponses];

export type RoutesUpdateData = {
    body: Route;
    path: {
        /**
         * A UUID string identifying this route.
         */
        id: string;
    };
    query?: never;
    url: '/routes/{id}/';
};

export type RoutesUpdateResponses = {
    200: Route;
};

export type RoutesUpdateResponse = RoutesUpdateResponses[keyof RoutesUpdateResponses];

export type TourismApiRegionalData = {
    body: RegionalTourismRequest;
    path?: never;
    query?: never;
    url: '/tourism/api/regional/';
};

export type TourismApiRegionalResponses = {
    201: RegionalTourismRequest;
};

export type TourismApiRegionalResponse = TourismApiRegionalResponses[keyof TourismApiRegionalResponses];

export type TourismPoisListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourism/pois/';
};

export type TourismPoisListResponses = {
    200: Array<TourismPoi>;
};

export type TourismPoisListResponse = TourismPoisListResponses[keyof TourismPoisListResponses];

export type TourismPoisReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this 관광지 POI.
         */
        id: string;
    };
    query?: never;
    url: '/tourism/pois/{id}/';
};

export type TourismPoisReadResponses = {
    200: TourismPoi;
};

export type TourismPoisReadResponse = TourismPoisReadResponses[keyof TourismPoisReadResponses];

export type TourismRecommendationRecommendData = {
    body: PoiRecommendationRequest;
    path?: never;
    query?: never;
    url: '/tourism/recommendation/recommend/';
};

export type TourismRecommendationRecommendResponses = {
    201: PoiRecommendationRequest;
};

export type TourismRecommendationRecommendResponse = TourismRecommendationRecommendResponses[keyof TourismRecommendationRecommendResponses];

export type TourismRecommendationRelatedData = {
    body: RelatedPoiRequest;
    path?: never;
    query?: never;
    url: '/tourism/recommendation/related/';
};

export type TourismRecommendationRelatedResponses = {
    201: RelatedPoiRequest;
};

export type TourismRecommendationRelatedResponse = TourismRecommendationRelatedResponses[keyof TourismRecommendationRelatedResponses];

export type TourismRelatedListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tourism/related/';
};

export type TourismRelatedListResponses = {
    200: Array<RelatedTourism>;
};

export type TourismRelatedListResponse = TourismRelatedListResponses[keyof TourismRelatedListResponses];

export type TourismRelatedReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this 연관 관광지.
         */
        id: string;
    };
    query?: never;
    url: '/tourism/related/{id}/';
};

export type TourismRelatedReadResponses = {
    200: RelatedTourism;
};

export type TourismRelatedReadResponse = TourismRelatedReadResponses[keyof TourismRelatedReadResponses];

export type TravelCoursesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/travel_courses/';
};

export type TravelCoursesListResponses = {
    200: Array<TravelCourse>;
};

export type TravelCoursesListResponse = TravelCoursesListResponses[keyof TravelCoursesListResponses];

export type TravelCoursesCreateData = {
    body: TravelCourse;
    path?: never;
    query?: never;
    url: '/travel_courses/';
};

export type TravelCoursesCreateResponses = {
    201: TravelCourse;
};

export type TravelCoursesCreateResponse = TravelCoursesCreateResponses[keyof TravelCoursesCreateResponses];

export type TravelCoursesMyListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/travel_courses/my/';
};

export type TravelCoursesMyListResponses = {
    200: Array<TravelCourse>;
};

export type TravelCoursesMyListResponse = TravelCoursesMyListResponses[keyof TravelCoursesMyListResponses];

export type TravelCoursesDeleteData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesDeleteResponses = {
    204: unknown;
};

export type TravelCoursesReadData = {
    body?: never;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesReadResponses = {
    200: TravelCourse;
};

export type TravelCoursesReadResponse = TravelCoursesReadResponses[keyof TravelCoursesReadResponses];

export type TravelCoursesPartialUpdateData = {
    body: TravelCourse;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesPartialUpdateResponses = {
    200: TravelCourse;
};

export type TravelCoursesPartialUpdateResponse = TravelCoursesPartialUpdateResponses[keyof TravelCoursesPartialUpdateResponses];

export type TravelCoursesUpdateData = {
    body: TravelCourse;
    path: {
        /**
         * A UUID string identifying this travel course.
         */
        id: string;
    };
    query?: never;
    url: '/travel_courses/{id}/';
};

export type TravelCoursesUpdateResponses = {
    200: TravelCourse;
};

export type TravelCoursesUpdateResponse = TravelCoursesUpdateResponses[keyof TravelCoursesUpdateResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};
