// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zRoute = z.object({
    id: z.optional(z.uuid().readonly()),
    created_at: z.optional(z.iso.datetime().readonly()),
    updated_at: z.optional(z.iso.datetime().readonly()),
    title: z.string().min(1).max(255),
    description: z.optional(z.string()),
    created_by: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    places: z.optional(z.array(z.uuid()).readonly())
});

export const zRegionalTourismRequest = z.object({
    area_cd: z.string().min(1),
    signgu_cd: z.string().min(1),
    base_ym: z.optional(z.string().min(1)),
    num_of_rows: z.optional(z.int().gte(1).lte(100)).default(20),
    page_no: z.optional(z.int().gte(1)).default(1)
});

export const zTourismPoi = z.object({
    id: z.optional(z.uuid().readonly()),
    hub_tats_cd: z.string().min(1).max(255),
    hub_tats_nm: z.string().min(1).max(255),
    map_x: z.number(),
    map_y: z.number(),
    area_cd: z.string().min(1).max(10),
    area_nm: z.string().min(1).max(100),
    signgu_cd: z.string().min(1).max(10),
    signgu_nm: z.string().min(1).max(100),
    hub_ctgry_lcls_nm: z.optional(z.string().max(100)),
    hub_ctgry_mcls_nm: z.optional(z.string().max(100)),
    hub_rank: z.int().gte(-9223372036854776000).lte(9223372036854776000),
    external_url: z.optional(z.url().max(200)),
    phone_number: z.optional(z.string().max(20)),
    address: z.optional(z.string()),
    created_at: z.optional(z.iso.datetime().readonly())
});

export const zPoiRecommendationRequest = z.object({
    latitude: z.number().gte(-90).lte(90),
    longitude: z.number().gte(-180).lte(180),
    radius_km: z.optional(z.number().gte(0.1).lte(50)).default(10),
    max_results: z.optional(z.int().gte(1).lte(100)).default(20)
});

export const zRelatedPoiRequest = z.object({
    poi_name: z.string().min(1),
    area_cd: z.string().min(1),
    signgu_cd: z.string().min(1)
});

export const zRelatedTourism = z.object({
    id: z.optional(z.uuid().readonly()),
    base_tats_nm: z.string().min(1).max(255),
    base_area_cd: z.string().min(1).max(10),
    base_area_nm: z.optional(z.string().max(100)),
    rite_tats_cd: z.string().min(1).max(255),
    rite_tats_nm: z.string().min(1).max(255),
    rite_regn_cd: z.string().min(1).max(10),
    rite_regn_nm: z.optional(z.string().max(100)),
    rite_ctgry_lcls_nm: z.optional(z.string().max(100)),
    rite_ctgry_mcls_nm: z.optional(z.string().max(100)),
    rite_rank: z.int().gte(-9223372036854776000).lte(9223372036854776000),
    created_at: z.optional(z.iso.datetime().readonly())
});

export const zTravelCourseRoute = z.object({
    route_id: z.uuid(),
    sequence: z.optional(z.int().gte(0).lte(9223372036854776000))
});

export const zTravelCourse = z.object({
    id: z.optional(z.uuid().readonly()),
    title: z.string().min(1).max(255),
    description: z.optional(z.string()),
    routes: z.array(zTravelCourseRoute)
});

export const zKakaomapDistanceListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zKakaomapMapListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zKakaomapOptimizeRouteCreateData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zKakaomapRouteListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zKakaomapSearchListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesListResponse = z.array(zRoute);

export const zRoutesCreateData = z.object({
    body: zRoute,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesCreateResponse = zRoute;

export const zRoutesCategoriesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesPreferencesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesPreferencesCreateData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesRecommendData = z.object({
    body: zRoute,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesRecommendResponse = zRoute;

export const zRoutesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesReadResponse = zRoute;

export const zRoutesPartialUpdateData = z.object({
    body: zRoute,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesPartialUpdateResponse = zRoute;

export const zRoutesUpdateData = z.object({
    body: zRoute,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesUpdateResponse = zRoute;

export const zTourismApiRegionalData = z.object({
    body: zRegionalTourismRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismApiRegionalResponse = zRegionalTourismRequest;

export const zTourismPoisListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismPoisListResponse = z.array(zTourismPoi);

export const zTourismPoisReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTourismPoisReadResponse = zTourismPoi;

export const zTourismRecommendationRecommendData = z.object({
    body: zPoiRecommendationRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRecommendationRecommendResponse = zPoiRecommendationRequest;

export const zTourismRecommendationRelatedData = z.object({
    body: zRelatedPoiRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRecommendationRelatedResponse = zRelatedPoiRequest;

export const zTourismRelatedListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRelatedListResponse = z.array(zRelatedTourism);

export const zTourismRelatedReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTourismRelatedReadResponse = zRelatedTourism;

export const zTravelCoursesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTravelCoursesListResponse = z.array(zTravelCourse);

export const zTravelCoursesCreateData = z.object({
    body: zTravelCourse,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTravelCoursesCreateResponse = zTravelCourse;

export const zTravelCoursesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesReadResponse = zTravelCourse;

export const zTravelCoursesPartialUpdateData = z.object({
    body: zTravelCourse,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesPartialUpdateResponse = zTravelCourse;

export const zTravelCoursesUpdateData = z.object({
    body: zTravelCourse,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesUpdateResponse = zTravelCourse;
