// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zUserDetail = z.object({
    id: z.optional(z.int().readonly()),
    username: z.string().min(1).max(50),
    email: z.email().min(1).max(254),
    login_method: z.optional(z.enum([
        'email',
        'kakao',
        'google'
    ])),
    profile_image_url: z.optional(z.union([
        z.url().max(500),
        z.null()
    ])),
    date_joined: z.optional(z.iso.datetime().readonly())
});

export const zUser = z.object({
    username: z.string().min(1).max(50),
    email: z.email().min(1).max(254),
    password: z.string().min(1),
    password_confirm: z.string().min(1),
    login_method: z.optional(z.enum([
        'email',
        'kakao',
        'google'
    ]))
});

export const zTokenObtainPair = z.object({
    username: z.string().min(1),
    password: z.string().min(1)
});

export const zTokenRefresh = z.object({
    refresh: z.string().min(1),
    access: z.optional(z.string().min(1).readonly())
});

export const zTokenVerify = z.object({
    token: z.string().min(1)
});

export const zCategory = z.object({
    id: z.optional(z.uuid().readonly()),
    name: z.string().min(1).max(255),
    description: z.optional(z.string()),
    icon: z.optional(z.string().max(255)),
    color: z.optional(z.string().max(255)),
    category_type: z.optional(z.enum([
        'korean',
        'western',
        'japanese',
        'chinese',
        'asian',
        'snack',
        'hamburger',
        'pizza',
        'seafood',
        'meat',
        'bakery',
        'pub'
    ])),
    is_active: z.optional(z.boolean()),
    created_at: z.optional(z.iso.datetime().readonly()),
    updated_at: z.optional(z.iso.datetime().readonly())
});

export const zPlace = z.object({
    id: z.optional(z.uuid().readonly()),
    created_at: z.optional(z.iso.datetime().readonly()),
    updated_at: z.optional(z.iso.datetime().readonly()),
    name: z.string().min(1).max(255),
    lat: z.number(),
    lng: z.number(),
    phone_number: z.optional(z.string().max(255)),
    avg_rating: z.optional(z.union([
        z.number(),
        z.null()
    ])),
    place_type: z.optional(z.enum([
        'RESTAURANT',
        'ATTRACTION',
        'SHOPPING',
        'ETC'
    ])),
    address: z.optional(z.string().max(255)),
    road_address: z.optional(z.string().max(255)),
    external_id: z.string().min(1).max(255),
    external_url: z.optional(z.url().max(200)),
    created_by: z.optional(z.union([
        z.int(),
        z.null()
    ]))
});

export const zPlaceRecommend = z.object({
    name: z.string().min(1).max(255),
    lat: z.number(),
    lng: z.number(),
    phone_number: z.union([
        z.string().min(1),
        z.null()
    ]),
    place_type: z.string().min(1),
    address: z.union([
        z.string().min(1),
        z.null()
    ]),
    road_address: z.union([
        z.string().min(1),
        z.null()
    ]),
    external_id: z.string().min(1),
    external_url: z.union([
        z.url().min(1),
        z.null()
    ])
});

export const zPlaceRecommendOutput = z.object({
    places: z.array(zPlaceRecommend)
});

export const zRoute = z.object({
    id: z.optional(z.uuid().readonly()),
    created_at: z.optional(z.iso.datetime().readonly()),
    updated_at: z.optional(z.iso.datetime().readonly()),
    title: z.string().min(1).max(255),
    description: z.optional(z.string()),
    created_by: z.optional(z.union([
        z.int(),
        z.null()
    ])),
    places: z.optional(z.array(z.uuid()).readonly())
});

export const zRouteRecommendationOutput = z.object({
    routes: z.array(z.record(z.string(), z.union([
        z.string(),
        z.null()
    ]))),
    user_location: z.record(z.string(), z.number())
});

export const zRegionalTourismRequest = z.object({
    area_cd: z.string().min(1),
    signgu_cd: z.string().min(1),
    base_ym: z.optional(z.string().min(1)),
    num_of_rows: z.optional(z.int().gte(1).lte(100)).default(20),
    page_no: z.optional(z.int().gte(1)).default(1)
});

export const zTourismPoi = z.object({
    id: z.optional(z.uuid().readonly()),
    hub_tats_cd: z.string().min(1).max(255),
    hub_tats_nm: z.string().min(1).max(255),
    map_x: z.number(),
    map_y: z.number(),
    area_cd: z.string().min(1).max(10),
    area_nm: z.string().min(1).max(100),
    signgu_cd: z.string().min(1).max(10),
    signgu_nm: z.string().min(1).max(100),
    hub_ctgry_lcls_nm: z.optional(z.string().max(100)),
    hub_ctgry_mcls_nm: z.optional(z.string().max(100)),
    hub_rank: z.int().gte(-2147483648).lte(2147483647),
    external_url: z.optional(z.url().max(200)),
    phone_number: z.optional(z.string().max(20)),
    address: z.optional(z.string()),
    created_at: z.optional(z.iso.datetime().readonly())
});

export const zPoiRecommendationRequest = z.object({
    latitude: z.number().gte(-90).lte(90),
    longitude: z.number().gte(-180).lte(180),
    radius_km: z.optional(z.number().gte(0.1).lte(50)).default(10),
    max_results: z.optional(z.int().gte(1).lte(100)).default(20)
});

export const zRelatedPoiRequest = z.object({
    poi_name: z.string().min(1),
    area_cd: z.string().min(1),
    signgu_cd: z.string().min(1)
});

export const zRelatedTourism = z.object({
    id: z.optional(z.uuid().readonly()),
    base_tats_nm: z.string().min(1).max(255),
    base_area_cd: z.string().min(1).max(10),
    base_area_nm: z.optional(z.string().max(100)),
    rite_tats_cd: z.string().min(1).max(255),
    rite_tats_nm: z.string().min(1).max(255),
    rite_regn_cd: z.string().min(1).max(10),
    rite_regn_nm: z.optional(z.string().max(100)),
    rite_ctgry_lcls_nm: z.optional(z.string().max(100)),
    rite_ctgry_mcls_nm: z.optional(z.string().max(100)),
    rite_rank: z.int().gte(-2147483648).lte(2147483647),
    created_at: z.optional(z.iso.datetime().readonly())
});

export const zTravelCourseRoute = z.object({
    route_id: z.uuid(),
    sequence: z.optional(z.int().gte(0).lte(2147483647))
});

export const zTravelCourse = z.object({
    id: z.optional(z.uuid().readonly()),
    title: z.string().min(1).max(255),
    description: z.optional(z.string()),
    routes: z.array(zTravelCourseRoute),
    start_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    end_date: z.optional(z.union([
        z.iso.date(),
        z.null()
    ])),
    destination: z.optional(z.union([
        z.string().max(255),
        z.null()
    ]))
});

export const zAccountsMeReadData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAccountsMeReadResponse = zUserDetail;

export const zAccountsSignupCreateData = z.object({
    body: zUser,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAccountsSignupCreateResponse = zUser;

export const zAuthTokenCreateData = z.object({
    body: zTokenObtainPair,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAuthTokenCreateResponse = zTokenObtainPair;

export const zAuthTokenRefreshCreateData = z.object({
    body: zTokenRefresh,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAuthTokenRefreshCreateResponse = zTokenRefresh;

export const zAuthTokenVerifyCreateData = z.object({
    body: zTokenVerify,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zAuthTokenVerifyCreateResponse = zTokenVerify;

export const zCategoriesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCategoriesListResponse = z.array(zCategory);

export const zCategoriesCreateData = z.object({
    body: zCategory,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zCategoriesCreateResponse = zCategory;

export const zCategoriesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zCategoriesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zCategoriesReadResponse = zCategory;

export const zCategoriesPartialUpdateData = z.object({
    body: zCategory,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zCategoriesPartialUpdateResponse = zCategory;

export const zCategoriesUpdateData = z.object({
    body: zCategory,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zCategoriesUpdateResponse = zCategory;

export const zPlacesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPlacesListResponse = z.array(zPlace);

export const zPlacesCreateData = z.object({
    body: zPlace,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zPlacesCreateResponse = zPlace;

export const zPlacesRecommendListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        lat: z.number(),
        lng: z.number(),
        max_distance_km: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        limit: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        category_filter: z.optional(z.union([
            z.array(z.string().min(1)),
            z.null()
        ]))
    })
});

export const zPlacesRecommendListResponse = zPlaceRecommendOutput;

export const zPlacesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPlacesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPlacesReadResponse = zPlace;

export const zPlacesPartialUpdateData = z.object({
    body: zPlace,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPlacesPartialUpdateResponse = zPlace;

export const zPlacesUpdateData = z.object({
    body: zPlace,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zPlacesUpdateResponse = zPlace;

export const zRoutesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesListResponse = z.array(zRoute);

export const zRoutesCreateData = z.object({
    body: zRoute,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesCreateResponse = zRoute;

export const zRoutesMyListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zRoutesMyListResponse = z.array(zRoute);

export const zRoutesRecommendListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.object({
        lat: z.number(),
        lng: z.number(),
        max_distance_km: z.optional(z.union([
            z.number(),
            z.null()
        ])),
        limit: z.optional(z.union([
            z.int(),
            z.null()
        ])),
        category_filter: z.optional(z.union([
            z.array(z.string().min(1)),
            z.null()
        ]))
    })
});

export const zRoutesRecommendListResponse = zRouteRecommendationOutput;

export const zRoutesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesReadResponse = zRoute;

export const zRoutesPartialUpdateData = z.object({
    body: zRoute,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesPartialUpdateResponse = zRoute;

export const zRoutesUpdateData = z.object({
    body: zRoute,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zRoutesUpdateResponse = zRoute;

export const zTourismApiRegionalData = z.object({
    body: zRegionalTourismRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismApiRegionalResponse = zRegionalTourismRequest;

export const zTourismPoisListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismPoisListResponse = z.array(zTourismPoi);

export const zTourismPoisReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTourismPoisReadResponse = zTourismPoi;

export const zTourismRecommendationRecommendData = z.object({
    body: zPoiRecommendationRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRecommendationRecommendResponse = zPoiRecommendationRequest;

export const zTourismRecommendationRelatedData = z.object({
    body: zRelatedPoiRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRecommendationRelatedResponse = zRelatedPoiRequest;

export const zTourismRelatedListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTourismRelatedListResponse = z.array(zRelatedTourism);

export const zTourismRelatedReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTourismRelatedReadResponse = zRelatedTourism;

export const zTravelCoursesListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTravelCoursesListResponse = z.array(zTravelCourse);

export const zTravelCoursesCreateData = z.object({
    body: zTravelCourse,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTravelCoursesCreateResponse = zTravelCourse;

export const zTravelCoursesMyListData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zTravelCoursesMyListResponse = z.array(zTravelCourse);

export const zTravelCoursesDeleteData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesReadData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesReadResponse = zTravelCourse;

export const zTravelCoursesPartialUpdateData = z.object({
    body: zTravelCourse,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesPartialUpdateResponse = zTravelCourse;

export const zTravelCoursesUpdateData = z.object({
    body: zTravelCourse,
    path: z.object({
        id: z.uuid()
    }),
    query: z.optional(z.never())
});

export const zTravelCoursesUpdateResponse = zTravelCourse;
