# Generated by Django 5.2.4 on 2025-07-22 04:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("phone_number", models.CharField(blank=True, max_length=255)),
                ("avg_rating", models.FloatField(blank=True, null=True)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("RESTAURANT", "Restaurant"),
                            ("ATTRACTION", "Attraction"),
                            ("SHOPPING", "Shopping"),
                            ("ETC", "Etc"),
                        ],
                        default="RESTAURANT",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255)),
                ("road_address", models.CharField(blank=True, max_length=255)),
                ("external_id", models.CharField(max_length=255, unique=True)),
                ("external_url", models.URLField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="places",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
