# Generated by Django 5.2.4 on 2025-07-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_alter_place_created_by_menuitem_placecategory_and_more"),
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="routeplace",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="routeplace",
            constraint=models.UniqueConstraint(
                fields=("route", "place"), name="unique_route_place"
            ),
        ),
        migrations.AddConstraint(
            model_name="routeplace",
            constraint=models.UniqueConstraint(
                fields=("route", "sequence"), name="unique_route_sequence"
            ),
        ),
    ]
