# Generated by Django 5.2.4 on 2025-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0002_alter_place_created_by_menuitem_placecategory_and_more"),
        ("routes", "0002_alter_routeplace_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="places",
            field=models.ManyToManyField(
                related_name="routes", through="routes.RoutePlace", to="places.place"
            ),
        ),
    ]
