# Generated by Django 5.2.4 on 2025-08-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("korean", "Korean"),
                    ("western", "Western"),
                    ("japanese", "Japanese"),
                    ("chinese", "Chinese"),
                    ("asian", "Asian"),
                    ("snack", "Snack"),
                    ("hamburger", "Hamburger"),
                    ("pizza", "Pizza"),
                    ("seafood", "Seafood"),
                    ("meat", "Meat"),
                    ("bakery", "Bakery"),
                    ("pub", "Pub"),
                ],
                max_length=255,
            ),
        ),
    ]
