# Generated by Django 5.2.4 on 2025-08-07 01:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="POIRecommendationCache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="추천 캐시 키"
                    ),
                ),
                ("recommended_pois", models.JSONField(verbose_name="추천된 POI 목록")),
                ("latitude", models.FloatField(verbose_name="위도")),
                ("longitude", models.FloatField(verbose_name="경도")),
                (
                    "radius_km",
                    models.FloatField(default=10.0, verbose_name="추천 반경(km)"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="만료 시간")),
            ],
            options={
                "verbose_name": "POI 추천 캐시",
                "verbose_name_plural": "POI 추천 캐시 목록",
                "db_table": "poi_recommendation_cache",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="poi_recomme_expires_f2f9fb_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="poi_recomme_latitud_cae487_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RelatedTourism",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "base_tats_nm",
                    models.CharField(max_length=255, verbose_name="기준관광지명"),
                ),
                (
                    "base_area_cd",
                    models.CharField(max_length=10, verbose_name="기준관광지지역코드"),
                ),
                (
                    "base_area_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="기준관광지지역명"
                    ),
                ),
                (
                    "base_signgu_cd",
                    models.CharField(
                        max_length=10, verbose_name="기준관광지시군구코드"
                    ),
                ),
                (
                    "base_signgu_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="기준관광지시군구명"
                    ),
                ),
                (
                    "rite_tats_cd",
                    models.CharField(max_length=255, verbose_name="연관관광지코드"),
                ),
                (
                    "rite_tats_nm",
                    models.CharField(max_length=255, verbose_name="연관관광지명"),
                ),
                (
                    "rite_regn_cd",
                    models.CharField(max_length=10, verbose_name="연관관광지지역코드"),
                ),
                (
                    "rite_regn_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연관관광지지역명"
                    ),
                ),
                (
                    "rite_signgu_cd",
                    models.CharField(
                        max_length=10, verbose_name="연관관광지시군구코드"
                    ),
                ),
                (
                    "rite_signgu_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연관관광지시군구명"
                    ),
                ),
                (
                    "rite_ctgry_lcls_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연관카테고리대분류명"
                    ),
                ),
                (
                    "rite_ctgry_mcls_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연관카테고리중분류명"
                    ),
                ),
                (
                    "rite_ctgry_scls_nm",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="연관카테고리소분류명"
                    ),
                ),
                ("rite_rank", models.IntegerField(verbose_name="연관순위")),
                ("base_ym", models.CharField(max_length=6, verbose_name="기준연월")),
            ],
            options={
                "verbose_name": "연관 관광지",
                "verbose_name_plural": "연관 관광지 목록",
                "db_table": "related_tourism",
                "indexes": [
                    models.Index(
                        fields=["base_area_cd", "base_signgu_cd"],
                        name="related_tou_base_ar_852c59_idx",
                    ),
                    models.Index(
                        fields=["rite_rank"], name="related_tou_rite_ra_a9ba43_idx"
                    ),
                    models.Index(
                        fields=["base_tats_nm"], name="related_tou_base_ta_339513_idx"
                    ),
                ],
                "unique_together": {("base_tats_nm", "rite_tats_cd")},
            },
        ),
        migrations.CreateModel(
            name="TourismAPICache",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="캐시 키"
                    ),
                ),
                ("data", models.JSONField(verbose_name="캐시된 데이터")),
                ("expires_at", models.DateTimeField(verbose_name="만료 시간")),
                (
                    "api_endpoint",
                    models.CharField(max_length=100, verbose_name="API 엔드포인트"),
                ),
                (
                    "request_params",
                    models.JSONField(default=dict, verbose_name="요청 파라미터"),
                ),
            ],
            options={
                "verbose_name": "관광 API 캐시",
                "verbose_name_plural": "관광 API 캐시 목록",
                "db_table": "tourism_api_cache",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="tourism_api_expires_dd4059_idx"
                    ),
                    models.Index(
                        fields=["api_endpoint"], name="tourism_api_api_end_8fe026_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TourismPOI",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hub_tats_cd",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="중심지관광지코드"
                    ),
                ),
                (
                    "hub_tats_nm",
                    models.CharField(max_length=255, verbose_name="중심지관광지명"),
                ),
                ("map_x", models.FloatField(verbose_name="X좌표값(경도)")),
                ("map_y", models.FloatField(verbose_name="Y좌표값(위도)")),
                ("area_cd", models.CharField(max_length=10, verbose_name="지역코드")),
                ("area_nm", models.CharField(max_length=100, verbose_name="지역명")),
                (
                    "signgu_cd",
                    models.CharField(max_length=10, verbose_name="시군구코드"),
                ),
                (
                    "signgu_nm",
                    models.CharField(max_length=100, verbose_name="시군구명"),
                ),
                (
                    "hub_ctgry_lcls_nm",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="중심지카테고리대분류명",
                    ),
                ),
                (
                    "hub_ctgry_mcls_nm",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="중심지카테고리중분류명",
                    ),
                ),
                ("hub_rank", models.IntegerField(verbose_name="중심지순위")),
                ("base_ym", models.CharField(max_length=6, verbose_name="기준연월")),
                ("external_url", models.URLField(blank=True, verbose_name="외부 링크")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
            ],
            options={
                "verbose_name": "관광지 POI",
                "verbose_name_plural": "관광지 POI 목록",
                "db_table": "tourism_poi",
                "indexes": [
                    models.Index(
                        fields=["area_cd", "signgu_cd"],
                        name="tourism_poi_area_cd_2d4573_idx",
                    ),
                    models.Index(
                        fields=["map_x", "map_y"], name="tourism_poi_map_x_56d613_idx"
                    ),
                    models.Index(
                        fields=["hub_rank"], name="tourism_poi_hub_ran_1fe7bb_idx"
                    ),
                ],
            },
        ),
    ]
